### ISSUE TITLE
[EVM] Add retry CLI command

### ISSUE THREAD

**Issue by nmlinaric** [sygmaprotocol/maintenance-utils#4]
# Description
We need CLI command that would enable retrying a failed transaction.

# Implementation details
Follow implementation pattern of already implemented CLI commands. This command should call `retry(string memory txHash)` function on bridge contract.

suggested CLI flags:
--env - define environment (required flag)
--txHash - deposit transaction hash

# Acceptance Criteria
[ ] Test CLI to resend a failed transaction
[ ] Update README with instuctions

**Comment by MakMuftic** [comment]
Closed with [this PR](https://github.com/sygmaprotocol/maintenance-utils/pull/12)
